title: Luis Eduardo Vargas
#logo: /assets/img/Imagen actualizada Enero 2025_small-modified.png
description: +57 320 813 2527 | vargascelyluiseduardo@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
